version: "3.9"

services:
  geth:
    image: blocknodes/ethereum:geth
    build:
      context: ./geth
      dockerfile: Dockerfile
    container_name: geth
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 3m
    ports:
      - 8545:8545
      - 8546:8546
      - 9191:9191
      - 30303:30303
    volumes:
      - ./data/geth:/data
      - ./jwt.hex:/shared/jwt.hex:ro
    networks:
      - ethnet
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  prysm-beacon:
    image: blocknodes/ethereum:prysm-beacon
    build:
      context: ./prysm-beacon
      dockerfile: Dockerfile
    container_name: prysm-beacon
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 1m
    volumes:
      - ./data/prysm-beacon:/data
      - ./jwt.hex:/shared/jwt.hex:ro
    depends_on:
      geth:
        condition: service_started
    networks:
      - ethnet
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

networks:
  ethnet:
    name: ethnet
