version: "3.9"

services:
  geth:
    image: blocknodes/ethereum:geth
    build:
      context: ./geth
      dockerfile: Dockerfile
    container_name: geth
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 3m
    ports:
      - 8545:8545
      - 8546:8546
      - 9191:9191
      - 30303:30303
    volumes:
      - ./data/geth:/data
      - ./jwt.hex:/shared/jwt.hex:ro
    networks:
      - ethnet
    healthcheck:
      test: [ "CMD", "curl", "-XPOST", "-H", "'Content-Type: application/json'", "--data", '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", false]}', "http://127.0.0.1:8545" ]
      interval: "10s"
      timeout: "10s"
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  prysm-beacon:
    image: blocknodes/ethereum:prysm-beacon
    build:
      context: ./prysm-beacon
      dockerfile: Dockerfile
    container_name: prysm-beacon
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 1m
    volumes:
      - ./data/prysm-beacon:/data
      - ./jwt.hex:/shared/jwt.hex:ro
    depends_on:
      geth:
        condition: service_started
    networks:
      - ethnet
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  explorer:
    image: alethio/ethereum-lite-explorer
    container_name: explorer
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - APP_NODE_URL=http://geth:8545
    depends_on:
      geth:
        condition: service_started
    networks:
      - ethnet
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"

networks:
  ethnet:
    name: ethnet
