global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: geth
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['geth:9191']
  - job_name: prysm
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: ['prysm-beacon:8080']
