---
version: '3'

x-common-settings: &common-settings
  restart: unless-stopped
  networks:
    - ethnet
  labels:
    logging: "promtail"
    logging_jobname: "containerlogs"
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "1"
      tag: "{{.Name}}"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=http://localhost:9090/
      - --web.route-prefix=/
      - --storage.tsdb.retention.time=7d
    ports:
      - 9090:9090
    <<: *common-settings

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
      - GF_PANELS_ENABLE_ALPHA=true
      # - GF_INSTALL_PLUGINS=grafana-polystat-panel
    volumes:
      - ./configs/grafana/provisioning/dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./configs/grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      - ./configs/grafana/dashboards/prometheus-overview.json:/var/lib/grafana/dashboards/prometheus-overview.json:ro
      - ./configs/grafana/dashboards/geth-overview.json:/var/lib/grafana/dashboards/geth-overview.json:ro
      - ./configs/grafana/dashboards/prysm-overview.json:/var/lib/grafana/dashboards/prysm-overview.json:ro
      - grafana:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_started
    ports:
      - 3000:3000
    <<: *common-settings

  loki:
    image: grafana/loki:2.7.4
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ethnet
    <<: *common-settings

  promtail:
    image:  grafana/promtail:2.7.4
    container_name: promtail
    volumes:
      - ./configs/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      loki:
        condition: service_started
    <<: *common-settings

networks:
  ethnet:
    external: true

volumes:
  prometheus: {}
  grafana: {}
